<a href="https://colab.research.google.com/github/mac-raj/PyTorch/blob/main/PyTorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Tut1

In [1]:
import torch
import numpy as np

**Empty Values Tensor**

In [2]:
# Print Empty values tensor
# Empty values tensor means values are not assign yet
x = torch.empty(1)
print(x)

tensor([1253.1230])


In [3]:
# Print one dimensional Empty values tensor of Size 3 
x = torch.empty(3)
print(x)

tensor([1.0585e-34, 0.0000e+00, 1.0601e-34])


In [4]:
# Print two dimensional Empty values tensor of Size 2,3 
x = torch.empty(2,3)
print(x)

tensor([[1.0606e-34, 0.0000e+00, 1.0607e-34],
        [0.0000e+00, 5.5432e+21, 4.5689e-41]])


In [5]:
# Print three dimensional Empty values tensor of Size 2,2,3 
x = torch.empty(2,2,3)
print(x)

tensor([[[9.8773e+21, 4.5689e-41, 9.8773e+21],
         [4.5689e-41, 4.4842e-44, 0.0000e+00]],

        [[8.9683e-44, 0.0000e+00, 1.0602e-34],
         [0.0000e+00, 2.4803e-43, 0.0000e+00]]])


**Random Values Tensor**

In [6]:
# Print one dimensional Random tensor
# Ranom values tensor means random values assigned 
x = torch.rand(1)
print(x)

tensor([0.5196])


In [7]:
# Print two dimensional Random values tensor of Size 3,2
x = torch.rand(3,2)
print(x)

tensor([[0.3921, 0.3944],
        [0.1070, 0.8602],
        [0.7693, 0.5149]])


In [8]:
# Print three dimensional Random values tensor of Size 2,3,2
x = torch.rand(2,3,2)
print(x)

tensor([[[0.0376, 0.9625],
         [0.4664, 0.1958],
         [0.9131, 0.0916]],

        [[0.0455, 0.7795],
         [0.5041, 0.1747],
         [0.6949, 0.9641]]])


**Zeroes Values Tensor**

In [9]:
# Print one dimensional zeroes values tensor
x = torch.zeros(1)
print(x)

tensor([0.])


In [10]:
# Print two dimensional zero values tensor of Size 3,4
x = torch.zeros(3,4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [11]:
# Print three dimensional zero values tensor of Size 2,3,4
x = torch.zeros(2,3,4)
print(x)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


**Ones Values Tensor**

In [12]:
# Print one dimensional ones values tensor
x = torch.ones(1)
print(x)

tensor([1.])


In [13]:
# Print two dimensional ones values tensor of Size 3,4
x = torch.ones(3,4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [14]:
# Print three dimensional ones values tensor of Size 2,3,4
x = torch.ones(2,3,4)
print(x)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


**Mathematical Operation with Tensor**

In [15]:
x = torch.rand(2,2)
y = torch.rand(2,2)


print(x)
print(y)
# Addition
print("Addition :", x+y)

# Substraction
print("Substraction :", x-y)

# Multiplication
print("Multiplication :", x*y)

# Division
print("Division :", x/y)

tensor([[0.3553, 0.1747],
        [0.6202, 0.9731]])
tensor([[0.6160, 0.5260],
        [0.3257, 0.1548]])
Addition : tensor([[0.9714, 0.7007],
        [0.9459, 1.1279]])
Substraction : tensor([[-0.2607, -0.3514],
        [ 0.2945,  0.8184]])
Multiplication : tensor([[0.2189, 0.0919],
        [0.2020, 0.1506]])
Division : tensor([[0.5768, 0.3320],
        [1.9041, 6.2884]])


In [16]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

# Modify y, Add x into y 
y.add_(x)
print(y)

# Modify x, Add y into x
x.add_(y)
print(x)

tensor([[0.9182, 0.7095],
        [0.8075, 0.3879]])
tensor([[0.3978, 0.8169],
        [0.8528, 0.1198]])
tensor([[1.3160, 1.5264],
        [1.6603, 0.5077]])
tensor([[2.2342, 2.2360],
        [2.4678, 0.8956]])


**Different method to Print row and columns of tensor**

In [17]:
x = torch.rand(5,2)
print(x)

tensor([[0.0709, 0.5005],
        [0.5952, 0.5678],
        [0.6353, 0.8725],
        [0.5357, 0.5254],
        [0.3308, 0.6982]])


In [18]:
#print only first column
print(x[:,0])

tensor([0.0709, 0.5952, 0.6353, 0.5357, 0.3308])


In [19]:
#print only first row
print(x[0,:])

tensor([0.0709, 0.5005])


In [20]:
# print only second column
print(x[:,1])

tensor([0.5005, 0.5678, 0.8725, 0.5254, 0.6982])


In [21]:
#Print only second row
print(x[1,:])

tensor([0.5952, 0.5678])


In [22]:
# Print all rows and all columns
print(x[:,:])

tensor([[0.0709, 0.5005],
        [0.5952, 0.5678],
        [0.6353, 0.8725],
        [0.5357, 0.5254],
        [0.3308, 0.6982]])


In [23]:
# Print particluar values using item
x = torch.rand(5,3)
print(x)
print(x[1,1].item())

tensor([[0.5554, 0.4095, 0.7589],
        [0.0320, 0.4255, 0.3128],
        [0.7879, 0.9415, 0.2065],
        [0.4216, 0.6264, 0.9356],
        [0.1641, 0.2472, 0.2116]])
0.4254978895187378


**Reshape tensor**

In [24]:
x = torch.rand(4,4)
print(x)

# Reshape tensor using view 
y = x.view(8,2)
print(y)

tensor([[0.7185, 0.7534, 0.1578, 0.2561],
        [0.2410, 0.7219, 0.7158, 0.9558],
        [0.8288, 0.4462, 0.1463, 0.9500],
        [0.8943, 0.5773, 0.4259, 0.5751]])
tensor([[0.7185, 0.7534],
        [0.1578, 0.2561],
        [0.2410, 0.7219],
        [0.7158, 0.9558],
        [0.8288, 0.4462],
        [0.1463, 0.9500],
        [0.8943, 0.5773],
        [0.4259, 0.5751]])


**Convert tensor into numpy array** 

In [25]:
# convert tensor to numpy
a = torch.ones(4)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1.])
[1. 1. 1. 1.]


In [26]:
type(a)

torch.Tensor

In [27]:
type(b)

numpy.ndarray

In [28]:
# Both tensor and numpy are run on diffenrent machine but both are store in same memory location
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2.])
[2. 2. 2. 2.]


**Convert numpy array into tensor**

In [29]:
a = np.ones(4)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1.]
tensor([1., 1., 1., 1.], dtype=torch.float64)


In [30]:
a = a+1
print(a)
print(b)

[2. 2. 2. 2.]
tensor([1., 1., 1., 1.], dtype=torch.float64)
